import type { Recipe } from "./types";

/** Стартовый каталог для прототипа — можно позже вынести в БД или импорт JSON. */
export const SEED_RECIPES: Recipe[] = [
  {
    id: "chicken-bulgur-veg",
    name: "Куриная грудка с булгуром и запечёнными овощами",
    teaser: "Копчёная паприка у овощей, лимон к курице — не скучнее обычной грудки.",
    minutes: 45,
    macrosPerServing: { kcal: 485, proteinG: 48, fatG: 12, carbsG: 48 },
    ingredients: [
      { name: "Куриная грудка", amount: 200, unit: "г" },
      { name: "Булгур сухой", amount: 55, unit: "г" },
      { name: "Кабачок", amount: 150, unit: "г" },
      { name: "Перец болгарский", amount: 100, unit: "г" },
      { name: "Лук репчатый", amount: 60, unit: "г" },
      { name: "Чеснок", amount: 2, unit: "зубч." },
      { name: "Оливковое масло", amount: 12, unit: "мл" },
      { name: "Лимон", amount: 0.25, unit: "шт" },
      { name: "Паприка копчёная", amount: 1, unit: "ч.л." },
    ],
  },
  {
    id: "beef-buckwheat",
    name: "Говядина тушёная с гречкой и морковью",
    teaser: "Томат + лавровый — глубже вкус, чем «просто мясо с крупой».",
    minutes: 90,
    macrosPerServing: { kcal: 520, proteinG: 42, fatG: 18, carbsG: 52 },
    ingredients: [
      { name: "Говядина для тушения", amount: 180, unit: "г" },
      { name: "Гречка сухая", amount: 60, unit: "г" },
      { name: "Морковь", amount: 80, unit: "г" },
      { name: "Лук репчатый", amount: 80, unit: "г" },
      { name: "Томатная паста", amount: 20, unit: "г" },
      { name: "Чеснок", amount: 2, unit: "зубч." },
      { name: "Лавровый лист", amount: 1, unit: "шт" },
      { name: "Растительное масло", amount: 8, unit: "мл" },
    ],
  },
  {
    id: "veg-omelette",
    name: "Пышный омлет с овощами и тёртым сыром",
    teaser: "Запекание в духовке — меньше масла, больше объёма.",
    minutes: 25,
    macrosPerServing: { kcal: 380, proteinG: 28, fatG: 24, carbsG: 14 },
    ingredients: [
      { name: "Яйца куриные", amount: 3, unit: "шт" },
      { name: "Молоко", amount: 40, unit: "мл" },
      { name: "Сыр твёрдый", amount: 35, unit: "г" },
      { name: "Шпинат свежий", amount: 40, unit: "г" },
      { name: "Помидоры черри", amount: 80, unit: "г" },
      { name: "Сливочное масло", amount: 5, unit: "г" },
      { name: "Соль, перец", amount: 1, unit: "щепотка" },
    ],
  },
  {
    id: "fish-steam-broccoli-rice",
    name: "Треска на пару с брокколи и бурым рисом",
    teaser: "Имбирь и соевый соус — азиатский акцент без лишних калорий.",
    minutes: 35,
    macrosPerServing: { kcal: 430, proteinG: 38, fatG: 8, carbsG: 52 },
    ingredients: [
      { name: "Филе трески (или хека)", amount: 200, unit: "г" },
      { name: "Рис бурый сухой", amount: 55, unit: "г" },
      { name: "Брокколи", amount: 150, unit: "г" },
      { name: "Имбирь свежий", amount: 10, unit: "г" },
      { name: "Соевый соус", amount: 15, unit: "мл" },
      { name: "Кунжутное масло", amount: 5, unit: "мл" },
      { name: "Лайм", amount: 0.5, unit: "шт" },
    ],
  },
  {
    id: "cottage-cheese-bake",
    name: "Творожная запеканка с ягодами",
    teaser: "Ваниль и цедра — десертный профиль без сахарной лавины.",
    minutes: 50,
    macrosPerServing: { kcal: 340, proteinG: 32, fatG: 12, carbsG: 28 },
    ingredients: [
      { name: "Творог 5%", amount: 200, unit: "г" },
      { name: "Яйца куриные", amount: 2, unit: "шт" },
      { name: "Манка", amount: 20, unit: "г" },
      { name: "Ягоды замороженные", amount: 80, unit: "г" },
      { name: "Йогурт натуральный", amount: 40, unit: "г" },
      { name: "Подсластитель по вкусу", amount: 1, unit: "порция" },
    ],
  },
  {
    id: "lentil-soup",
    name: "Крем-суп из красной чечевицы с кокосом",
    teaser: "Карри и кокосовое молоко — насыщенно, как в кафе.",
    minutes: 40,
    macrosPerServing: { kcal: 395, proteinG: 18, fatG: 14, carbsG: 48 },
    ingredients: [
      { name: "Чечевица красная сухая", amount: 90, unit: "г" },
      { name: "Морковь", amount: 60, unit: "г" },
      { name: "Лук репчатый", amount: 60, unit: "г" },
      { name: "Чеснок", amount: 2, unit: "зубч." },
      { name: "Кокосовое молоко", amount: 100, unit: "мл" },
      { name: "Паста карри", amount: 15, unit: "г" },
      { name: "Овощной бульон", amount: 400, unit: "мл" },
    ],
  },
  {
    id: "turkey-pasta",
    name: "Паста из твёрдых сортов с фаршем индейки",
    teaser: "Базилик свежий + пармезан в конце — «ресторанный» финал.",
    minutes: 35,
    macrosPerServing: { kcal: 560, proteinG: 44, fatG: 16, carbsG: 68 },
    ingredients: [
      { name: "Паста цельнозерновая сухая", amount: 80, unit: "г" },
      { name: "Фарш индейки", amount: 150, unit: "г" },
      { name: "Помидоры в собственном соку", amount: 200, unit: "г" },
      { name: "Лук репчатый", amount: 50, unit: "г" },
      { name: "Чеснок", amount: 2, unit: "зубч." },
      { name: "Сыр пармезан", amount: 15, unit: "г" },
      { name: "Базилик свежий", amount: 10, unit: "г" },
      { name: "Оливковое масло", amount: 10, unit: "мл" },
    ],
  },
  {
    id: "tuna-bowl",
    name: "Поке-миска с тунцом, авокадо и киноа",
    teaser: "Сезам и огурец — хруст и умами без жарки.",
    minutes: 25,
    macrosPerServing: { kcal: 510, proteinG: 36, fatG: 22, carbsG: 48 },
    ingredients: [
      { name: "Тунец консервированный в собственном соку", amount: 150, unit: "г" },
      { name: "Киноа сухая", amount: 45, unit: "г" },
      { name: "Авокадо", amount: 0.5, unit: "шт" },
      { name: "Огурец свежий", amount: 100, unit: "г" },
      { name: "Морковь по-корейски (опционально)", amount: 40, unit: "г" },
      { name: "Соевый соус", amount: 12, unit: "мл" },
      { name: "Масло кунжутное", amount: 5, unit: "мл" },
      { name: "Кунжут", amount: 5, unit: "г" },
    ],
  },
];

export function recipeById(id: string): Recipe | undefined {
  return SEED_RECIPES.find((r) => r.id === id);
}
